services:
  - type: web
    name: reelmate-backend
    env: python
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: |
      python manage.py migrate && \
      gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: ALLOWED_HOSTS
        value: "reelmate-backend.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://reelmate-backend.onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DB_SSL_REQUIRE
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: reelmate-db
          property: connectionString

databases:
  - name: reelmate-db
    plan: free
